### ISSUE TITLE
The executable was signed with invalid entitlements.

### ISSUE THREAD

**Issue by iYsood** [iMokhles/SCfeatures#1]
Hello Mokhles, Thanks for this project.

I've issue (The executable was signed with invalid entitlements.)

How can i fix it?

**Comment by beBoss** [comment]
same for me

**Comment by betrisey** [comment]
I fixed it by replacing the team ID by mine in SCFeaturesApp/app.entitlements
You can find your Team ID here: https://developer.apple.com/account/#/membership

**Comment by iYsood** [comment]
@betrisey  It's done <3, 
Thank you
